### ISSUE TITLE
hello, i need a teammate

### ISSUE THREAD

**Issue by abdouahabch7** [gamerbenyt/justenougharmour#1]
**im a Modrinth creator (https://modrinth.com/user/abdouahabch7).**
im gathering members for an organization to keep posting new content

**if you are interested**
here's my discord join and we will talk more https://discord.gg/tcDhZQsjeE

**you will get 25% of the revenue**
i will get 25% and the two left members will get 25% each

### good luck

**Comment by gamerbenyt** [comment]
bro im waiting for you to reply on discord
